<template>
  <svg
    width="48"
    height="48"
    viewBox="0 0 48 48"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect width="48" height="48" rx="6" fill="#D54941" fill-opacity="0.1" />
    <rect
      x="1"
      y="1"
      width="24"
      height="24"
      rx="5"
      fill="#D54941"
      fill-opacity="0.2"
    />
    <rect
      x="8"
      y="8"
      width="28"
      height="28"
      rx="5"
      fill="#D54941"
      fill-opacity="0.3"
    />
    <rect
      x="16"
      y="16"
      width="31"
      height="31"
      rx="5"
      fill="#D54941"
      fill-opacity="0.4"
    />
    <rect
      x="0.5"
      y="0.5"
      width="47"
      height="47"
      rx="5.5"
      stroke="var(--theme-component-border)"
    />
  </svg>
</template>

<script>
export default {};
</script>
