const fontSizeSteps = {
  1: [
    { name: "--td-font-size-link-small", value: "12px" },
    { name: "--td-font-size-link-medium", value: "13px" },
    { name: "--td-font-size-link-large", value: "14px" },
    { name: "--td-font-size-mark-small", value: "12px" },
    { name: "--td-font-size-mark-medium", value: "13px" },
    { name: "--td-font-size-body-small", value: "12px" },
    { name: "--td-font-size-body-medium", value: "13px" },
    { name: "--td-font-size-body-large", value: "14px" },
    { name: "--td-font-size-title-small", value: "13px" },
    { name: "--td-font-size-title-medium", value: "14px" },
    { name: "--td-font-size-title-large", value: "16px" },
    { name: "--td-font-size-headline-small", value: "21px" },
    { name: "--td-font-size-headline-medium", value: "24px" },
    { name: "--td-font-size-headline-large", value: "28px" },
    { name: "--td-font-size-display-medium", value: "36px" },
    { name: "--td-font-size-display-large", value: "48px" },
  ], // 超小号
  2: [
    { name: "--td-font-size-link-small", value: "12px" },
    { name: "--td-font-size-link-medium", value: "13px" },
    { name: "--td-font-size-link-large", value: "15px" },
    { name: "--td-font-size-mark-small", value: "12px" },
    { name: "--td-font-size-mark-medium", value: "13px" },
    { name: "--td-font-size-body-small", value: "12px" },
    { name: "--td-font-size-body-medium", value: "13px" },
    { name: "--td-font-size-body-large", value: "15px" },
    { name: "--td-font-size-title-small", value: "13px" },
    { name: "--td-font-size-title-medium", value: "15px" },
    { name: "--td-font-size-title-large", value: "17px" },
    { name: "--td-font-size-headline-small", value: "22px" },
    { name: "--td-font-size-headline-medium", value: "25px" },
    { name: "--td-font-size-headline-large", value: "31px" },
    { name: "--td-font-size-display-medium", value: "40px" },
    { name: "--td-font-size-display-large", value: "52px" },
  ], // 小号
  3: [
    { name: "--td-font-size-link-small", value: "12px" },
    { name: "--td-font-size-link-medium", value: "14px" },
    { name: "--td-font-size-link-large", value: "16px" },
    { name: "--td-font-size-mark-small", value: "12px" },
    { name: "--td-font-size-mark-medium", value: "14px" },
    { name: "--td-font-size-body-small", value: "12px" },
    { name: "--td-font-size-body-medium", value: "14px" },
    { name: "--td-font-size-body-large", value: "16px" },
    { name: "--td-font-size-title-small", value: "14px" },
    { name: "--td-font-size-title-medium", value: "16px" },
    { name: "--td-font-size-title-large", value: "20px" },
    { name: "--td-font-size-headline-small", value: "24px" },
    { name: "--td-font-size-headline-medium", value: "28px" },
    { name: "--td-font-size-headline-large", value: "36px" },
    { name: "--td-font-size-display-medium", value: "48px" },
    { name: "--td-font-size-display-large", value: "64px" },
  ], // 默认
  4: [
    { name: "--td-font-size-link-small", value: "13px" },
    { name: "--td-font-size-link-medium", value: "15px" },
    { name: "--td-font-size-link-large", value: "17px" },
    { name: "--td-font-size-mark-small", value: "13px" },
    { name: "--td-font-size-mark-medium", value: "15px" },
    { name: "--td-font-size-body-small", value: "13px" },
    { name: "--td-font-size-body-medium", value: "15px" },
    { name: "--td-font-size-body-large", value: "17px" },
    { name: "--td-font-size-title-small", value: "15px" },
    { name: "--td-font-size-title-medium", value: "17px" },
    { name: "--td-font-size-title-large", value: "21px" },
    { name: "--td-font-size-headline-small", value: "25px" },
    { name: "--td-font-size-headline-medium", value: "29px" },
    { name: "--td-font-size-headline-large", value: "37px" },
    { name: "--td-font-size-display-medium", value: "49px" },
    { name: "--td-font-size-display-large", value: "65px" },
  ], // 大号
  5: [
    { name: "--td-font-size-link-small", value: "14px" },
    { name: "--td-font-size-link-medium", value: "17px" },
    { name: "--td-font-size-link-large", value: "20px" },
    { name: "--td-font-size-mark-small", value: "14px" },
    { name: "--td-font-size-mark-medium", value: "17px" },
    { name: "--td-font-size-body-small", value: "14px" },
    { name: "--td-font-size-body-medium", value: "17px" },
    { name: "--td-font-size-body-large", value: "20px" },
    { name: "--td-font-size-title-small", value: "17px" },
    { name: "--td-font-size-title-medium", value: "20px" },
    { name: "--td-font-size-title-large", value: "23px" },
    { name: "--td-font-size-headline-small", value: "32px" },
    { name: "--td-font-size-headline-medium", value: "38px" },
    { name: "--td-font-size-headline-large", value: "47px" },
    { name: "--td-font-size-display-medium", value: "59px" },
    { name: "--td-font-size-display-large", value: "74px" },
  ], // 特大号
};

const fontSizeLabels = {
  1: "超小号",
  2: "小号",
  3: "默认",
  4: "大号",
  5: "特大号",
};

export { fontSizeLabels, fontSizeSteps };
