#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged && log_emails=$(git config user.email) && if [[ ${log_emails} =~ '@tencent.com' ]];then echo 本地提交邮箱 $log_emails 校验非法，需要本地更改重新提交 && exit 2;else echo 邮箱 $log_emails 校验通过;fi
