# 文件名建议统一为 preview-publish
# 应用 preview.yml 的 demo
name: PREVIEW_PUBLISH

on:
  workflow_run:
    workflows: ['MAIN_PULL_REQUEST']
    types:
      - completed

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: build-site
        run: npm run site:preview
  call-preview:
    uses: Tencent/tdesign/.github/workflows/preview.yml@main
    secrets:
      TDESIGN_SURGE_TOKEN: ${{ secrets.TDESIGN_SURGE_TOKEN }}
