name: publish-site-components

permissions:
  contents: read
  id-token: write

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - packages/site-components/package.json

  workflow_dispatch:

jobs:
  publish-site-components:
    if: github.repository == 'Tencent/tdesign'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: pnpm install

      - run: pnpm -F @tdesign/site-components run build

      - run: npm i -g npm@latest

      - name: Publish Package
        run: pnpm -F @tdesign/site-components publish

  auto-upgrade-tdesign-site-components:
    needs: publish-site-components
    runs-on: ubuntu-latest
    steps:
      - name: upgrade @tdesign/site-components
        uses: TDesignOteam/tdesign-pr-trigger-action@develop
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          trigger: /upgrade-deps
          deps: '@tdesign/site-components'
          package-manager: pnpm
