name: publish-site-components

permissions:
  contents: read
  id-token: write

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - packages/site-components/package.json

  workflow_dispatch:

jobs:
  publish-site-components:
    if: github.event_name == 'workflow_dispatch' || (github.repository == 'Tencent/tdesign' && startsWith(github.head_ref, 'release/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - run: pnpm install

      - run: pnpm -F @tdesign/site-components run build

      # 为了兼容 oidc 特指定 node 版本最小为 24
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Publish Package
        run: pnpm -F @tdesign/site-components publish --no-git-checks

  auto-upgrade-tdesign-site-components:
    needs: publish-site-components
    runs-on: ubuntu-latest
    steps:
      - name: upgrade @tdesign/site-components
        uses: TDesignOteam/tdesign-pr-trigger-action@develop
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          trigger: /upgrade-deps
          deps: '@tdesign/site-components'
          package-manager: pnpm
